sudo: false

language: perl

perl:
  - "5.22"
  - "5.24"

before_install:
  - cpanm --notest
    Devel::Cover::Report::Coveralls
    IO::Socket::SSL Mojolicious@7.26
    Mojolicious::Plugin::Qooxdoo@0.905
    Mojo::SQLite@0.011 Config::Grammar@1.10

script:
  - cover -test -report coveralls
  - perl Makefile.PL
  - make thirdparty
  - perl -I thirdparty/lib/perl5/ -I lib thirdparty/bin/mojo  generate  callbackery_app


